In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import gensim
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=12543d0007b2efa12c9cf31ce35e5ea92c16f2153dc2e79ee792c1fc50cb4771
  Stored in directory: /root/.cache/pip/wheels/40/b3/0f/a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget


In [ ]:
import os

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [ ]:
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
stop_words = set(stopwords.words('english'))
story = []
data_path = '/content/data'

for filename in os.listdir(data_path):
    file_path = os.path.join(data_path, filename)

    # Ensure it's a file before attempting to open it
    if os.path.isfile(file_path):
        with open(file_path, 'r', encoding='utf-8', errors='replace') as f:
            corpus = f.read()
            raw_sent = sent_tokenize(corpus)
            for sent in raw_sent:
              filtered_tokens = [word for word in simple_preprocess(sent) if word not in stop_words]
              story.append(filtered_tokens)

In [ ]:
len(story)

145020

In [ ]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(4395873, 4579345)

In [ ]:
model.wv.most_similar('daenerys')

[('stormborn', 0.9141404032707214),
 ('unburnt', 0.8778371810913086),
 ('targaryen', 0.8386738300323486),
 ('myrcella', 0.8225621581077576),
 ('viserys', 0.8179495930671692),
 ('dorne', 0.8163506984710693),
 ('elia', 0.8109842538833618),
 ('westeros', 0.8041107058525085),
 ('brokered', 0.802090048789978),
 ('court', 0.7985813021659851)]

In [ ]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [ ]:
model.wv['king'].shape

(100,)

In [ ]:
model.wv.similarity('arya','sansa')

0.81141675

In [ ]:
model.wv.get_normed_vectors()

array([[ 0.06220648,  0.12910213, -0.01446984, ..., -0.0829751 ,
        -0.15303361,  0.19595529],
       [-0.14888024,  0.06253996,  0.10781557, ..., -0.06538516,
        -0.20698793,  0.13516302],
       [-0.04404606,  0.04942713, -0.09370086, ..., -0.14234243,
         0.11550225, -0.08777818],
       ...,
       [ 0.04569204,  0.13294174, -0.01190751, ..., -0.12479356,
        -0.03875141,  0.06576061],
       [-0.0937979 ,  0.02516878,  0.19443558, ..., -0.07475799,
         0.09518324,  0.11636173],
       [-0.0432865 ,  0.10806452,  0.05151921, ..., -0.14194545,
         0.01574014, -0.00042047]], dtype=float32)

In [ ]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [ ]:
y = model.wv.index_to_key

In [ ]:
y

['said',
 'lord',
 'would',
 'one',
 'ser',
 'could',
 'man',
 'king',
 'men',
 'back',
 'well',
 'like',
 'jon',
 'father',
 'old',
 'hand',
 'even',
 'tyrion',
 'never',
 'know',
 'see',
 'made',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'long',
 'might',
 'us',
 'come',
 'face',
 'still',
 'head',
 'red',
 'way',
 'boy',
 'page',
 'must',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 'little',
 'took',
 'came',
 'though',
 'say',
 'three',
 'away',
 'dead',
 'son',
 'blood',
 'take',
 'go',
 'half',
 'make',
 'arya',
 'saw',
 'day',
 'white',
 'jaime',
 'first',
 'look',
 'want',
 'much',
 'enough',
 'sword',
 'tell',
 'girl',
 'bran',
 'great',
 'looked',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'wall',
 'every',
 'heard',
 'sansa',
 'let',
 'yet',
 'went',
 'turned',
 'dany',
 'need',
 'behind',
 'around',
 'woman',
 'another',
 'snow',
 'beneath',
 'across',
 'knight',
 'keep',
 'grace',
 'found',
 'gold',
 'last',
 'cersei',
 'castle',
 '

In [ ]:
len(y)

17310

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=3)

In [ ]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [ ]:
X[:5]

array([[ 0.48768198, -0.02466163,  0.20281047],
       [ 0.38750282, -0.5581714 ,  0.41218153],
       [ 0.5087006 ,  0.03279981, -0.3390863 ],
       [ 0.01168744, -0.1424324 , -0.03326559],
       [ 0.29105672, -0.49973634,  0.5466303 ]], dtype=float32)

In [ ]:
X.shape

(17310, 3)

In [ ]:
import plotly.express as px

In [ ]:
fig = px.scatter_3d(X[:500],x=0,y=1,z=2,color=y[:500])
fig.show()

In [ ]:
# import gensim.downloader as api
# model = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
# model['man'].shape

(300,)

In [ ]:
# model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [ ]:
# model.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [ ]:
# model.similarity('man','woman')

0.76640123

In [ ]:
# model.similarity('man','PHP')

-0.032995153

In [ ]:
# model.doesnt_match(['PHP','java','monkey'])

'monkey'

In [ ]:
# vec = model['king'] - model['man'] + model['woman']
# model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [ ]:
# vec2 = model['INR'] - model['India'] + model['England']
# model.most_similar([vec2])

[('INR', 0.6442341208457947),
 ('GBP', 0.5040826797485352),
 ('£_##.###m', 0.4540838301181793),
 ('England', 0.44649264216423035),
 ('£', 0.43340998888015747),
 ('Â_£', 0.4307197630405426),
 ('stg###', 0.4299262464046478),
 ('£_#.##m', 0.42561301589012146),
 ('Pounds_Sterling', 0.42512619495391846),
 ('GBP##', 0.42464491724967957)]